### ISSUE TITLE
[Question] is there a way to tell wslgit.exe's version?

### ISSUE THREAD

**Issue by ElTopo** [andy-5/wslgit#105]
Currently wslgit.exe seems to pass all args to wsl's git, so 
`wslgit.exe --version `
prints out git's version.

Is there a way to print wslgit.exe's own version?

**Comment by andy-5** [comment]
Right now, there is no way to find out wslgit's own version. But I can see that it could be useful.

The only way I can think of is to compare checksums of the various released binaries.

**Comment by ElTopo** [comment]
@andy-5 Thanks. Maybe we can change this issue to [Feature Request]?

**Comment by andy-5** [comment]
I've pushed some changes to the develop branch so that the current version number is now also logged if the environment variable `WSLGIT_ENABLE_LOGGING` is set to `1`.

If enabled, you will find a `wslgit.log` next to `wslgit.exe` with logs for executed commands - and now also the version number of the `wslgit` executable.
