### ISSUE TITLE
Update code or discontinue support upon spring release of Windows

### ISSUE THREAD

**Issue by DarthSpock** [andy-5/wslgit#25]
Since 17093, new exciting possibilities exist now including relevance to this project. Specifically for this project:

Per the Release Notes: 

> Improved case sensitivity support in DrvFs.

See details in release notes for options.

> You can now use forward slashes in Windows paths when mounting DrvFs, e.g.: sudo mount -t drvfs //server/share /mnt/share

It works the other way too for windows paths you want to navigate to in Linux.

From your project page: 

> For these two to interoperate, this tool translates paths between the Windows (C:\Foo\Bar) and Linux (/mnt/c/Foo/Bar) representations.

Translation no longer needed by this project. Therefore suspecting this project will no longer be needed once the stable release of Windows happens this spring. Incidentally VSCode for Linux can be run also, once again defeating the purpose of this project.

**Comment by jedmao** [comment]
https://blogs.windows.com/windowsexperience/2018/02/07/announcing-windows-10-insider-preview-build-17093-pc/

**Comment by jedmao** [comment]
> **Better file handling via folder level case sensitivity:** One of the tricky problems sharing data between Linux and Windows comes down to file case handling.  Windows isn’t case sensitive, Linux is.  In the past WSL used exclusively process-based case sensitivity.  Starting in 17089, NTFS has a new flag that can be set on directories to indicate all operations in those directories should be treated as case sensitive, which allows Windows applications to correctly open files that differ only by case.
> 
> For an even more detailed list of WSL updates, read the [WSL release notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17093).

**Comment by DarthSpock** [comment]
Knew there was one I was forgetting to add here.

**Comment by andy-5** [comment]
I would be happy to be proven wrong, but I do not see how any of these new features is making `wslgit` obsolete.

The new features are great, but for use in VS Code, `wslgit` is still required to translate the output of Git installed inside WSL so that the VS Code Git plugin can parse it correctly. No feature of WSL itself can fix this, as the Linux version of Git will always print out Linux paths. Only native support of Git installed inside WSL in VS Code would make `wslgit` unnessecary.

I'm closing this issue, since there is nothing to do here. Feel free to suggest specific changes or improvements to `wslgit`. You're also welcome to discuss how upcoming features of WSL could affect `wslgit`.
