### ISSUE TITLE
Fatal Error When Used With VScode

### ISSUE THREAD

**Issue by mattoni** [andy-5/wslgit#31]
I'm getting this error: `fatal: Not a git repository (or any parent up to mount point /mnt/c)` when attempting to follow the set up instructions for vscode. I saved the exe and pointed vscode to it, but no dice. I can use wsl git independently, and windows git independently, but it doesn't seem to want to work with this solution :/

**Comment by andy-5** [comment]
In some cases this output is expected, e.g. if you have the settings page open (or any other file outside of a git repository). In that case, you should not worry about these messages.

Otherwise, does VS Code detect wslgit correctly? The first two lines of the git output should read something like
```
Looking for git in: C:\SOME\PATH\wslgit.exe
Using git 2.7.4 from C:\SOME\PATH\wslgit.exe
```
Also, if you change a file tracked by git, does it show up in the Source Control panel in VS Code?

**Comment by andy-5** [comment]
I'm closing this, since there was no further reply and the issue seems to be caused only by files outside of a git repository.
