### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by 1ne8ight7even** [andy-5/wslgit#4]
Hey, I'm using Windows 10 1709 and VS Code 1.17.2.

I renamed wslgit.exe into git.exe and added it to the PATH variable.

VSCode settings
`    "git.enabled": true,
    "git.path": "C:\\Users\\<username>\\AppData\\Local\\Git\\git.exe",
`
I can use git with PowerShell, CMD and of course Bash for Ubuntu, but not in VS Code.

**Comment by andy-5** [comment]
Are you using an *old* WSL Beta environment (Bash on Windows) or did you install the Linux Distribution from the Store (which is the new way since the Fall Creators Update)?

If `C:\Users\<username>\AppData\Local\Git\git.exe --version` works in PowerShell or in CMD, then you probably have an old style environment, because wslgit currently does not support the new WSL Linux environments.

What exactly does not work in VS Code? Any errors? Does it detect the repository if you open a version controlled directory?

Could you post the output of the Git console in VS Code?

**Comment by 1ne8ight7even** [comment]
I think it's the old Beta, because it's called "Bash on Ubuntu on Windows". I'll try it with the Ubuntu Distribution from the Microsoft store.

VS Code just doesn't recognize that the project has git.

**Comment by andy-5** [comment]
Ok. However, it won't work with the new version from the store, as they use different executables to call into the WSL environment. I haven't implemented support for them, currently.

Can you post the output of the git console from VS Code? It should contain the git commands VS Code tries to run to detect the git repository, etc.
You can then run the same commands in a CMD shell to check their outputs.

**Comment by 1ne8ight7even** [comment]
Cool.

**Comment by andy-5** [comment]
I just released a new version that should hopefully fix this. Please try the latest release here:

https://github.com/andy-5/wslgit/releases/tag/v0.3.0

**Comment by 1ne8ight7even** [comment]
I'll try it this evening and give you some feedback.

**Comment by 1ne8ight7even** [comment]
JFYI: Your fix is working.

**Comment by andy-5** [comment]
Great, thanks for reporting back.
