### ISSUE TITLE
parentheses and pipes in parameters cause failures

### ISSUE THREAD

**Issue by diablodale** [andy-5/wslgit#54]
parenthesis `)(` and pipe `|` can not be used in arguments to wslgit. It fails to run git.

A bug seen in gitlens has exposed the need for richer shell escaping in wslgit. The parenthesis `)(` and pipe `|` should be supported as text and not as command processor special characters. The related GitLens bug is https://github.com/eamodio/vscode-gitlens/issues/526

## Setup

* wslgit v0.6.0 or newer such as the commits which incorporate the fixes for escaping spaces and changing to cwd, available at https://github.com/diablodale/wslgit/commit/ec757bc02e82f8a84affa28d714b761001ce0e4f
* Microsoft Windows [Version 10.0.17763.55]
* WSL with Ubuntu 16.04.5 LTS

## Repo

1. Setup wsl with code from above repo commit
2. You can use the basic setup or the advanced BASH_ENV setup. Both reproduce the problem
3. In CMD, change directory to a valid git repo
4. `wslgit.exe config --get-regex "user.(name|email)"`

## Expected

```
user.name Dale Phurrough
user.email dale@hidale.com
```

## Actual Result

Basic setup
```
bash: syntax error near unexpected token `('
```

Advanced BASH_ENV setup
```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cd /mnt/n/opsworkspace/zfs-auto-snapshot && git config --get-regex user.(name|email)'
```

## Workaround/fix

You can force it to work by escaping as follows. The quotes get it past the CMD interpreter, then the backslashes work in BASH. Naturally, this is messy and should be automated in code.
```
wslgit.exe config --get-regex "user.\(name\|email\)"
```

**Comment by andy-5** [comment]
Yeah, I've expected something like this, but never run into a problem myself, so thanks for bringing this up.

Interestingly, directly running
```
wsl git config --get-regex "user.(name|email)"
```
from CMD works without escaping. But using wslgit, this does not work, as the regex part will not be quoted (only arguments with spaces are quoted, and as of the latest commit, only for an interactive shell).

So, the possible solutions would be to either escape these special characters, or to properly quote the arguments (without re-introducing the problems from #46).

**Comment by andy-5** [comment]
That crate looks useful. As far as I can see, it quotes every string containing special characters using single quotes `'` (so shells shouldn't interpret the content) and escapes all single quotes inside the string.

It is probably a good idea to use that, instead of trying to come up with another solution. Also, that crate seems to be widely used, as it is a dependency of cargo itself.

Different behavior between using bash vs. wsl directly could complicate this, as you experienced. Maybe we should just drop the functionality for using an interactive bash shell in a future release and provide some recommendation for setting up tools like `ssh-agent` or `gpg-agent`. At least according to the reported issues, many seem to use the non-interactive mode anyway.

**Comment by andy-5** [comment]
With #74 merged, your initial example now works correctly for both interactive and non-interactive settings. 

But your examples from https://github.com/andy-5/wslgit/issues/54#issuecomment-430574324 only work with the non-interactive shell setting. Using an interactive bash shell, they still fail.

I'll keep this issue open for the interactive shell use case.

**Comment by carlolars** [comment]
After I posted PR #74 I started to click around trying git-stuff in VSCode and also in [Fork](https://fork.dev/) (where I've replaced their own git.exe with a renamed wslgit) and I found some stuff that was not working.

But now I think I have solved it, or at least it works for me, both VSCode's git and gitlense, and Fork.  
I'll make a PR so you can review and try it if you'd like.

Basically, instead of quoting I append a single space-character to arguments that contain invalid characters. A space character in an argument seems to make it become correctly quoted on the way somewhere, unfortunately I don't know where.

**Comment by andy-5** [comment]
That's an interesting and helpful observation. Is that maybe a feature of `wsl.exe`? Have you tested it for both the interactive and the non-interactive shell configurations?

Anyway, thank you for testing this and creating a PR, I'll take a look at it when I have some time.

**Comment by andy-5** [comment]
With the unified quoting for interactive/non-interactive shells from #76, everything works now for both configurations, except the example with the \` character (which works without the \`):
```
wslgit.exe config --get-regex "user.(name|email|`\$&)"
```
But as commented on the PR, this example does not work on Linux/WSL either, so I think it is not really a problem. If you do find a real example where this is a problem, please file a new issue.
