### ISSUE TITLE
Possibility for work with any command?

### ISSUE THREAD

**Issue by leonardovilarinho** [andy-5/wslgit#6]
Hi @andy-5,

Exist any possibility for apply this program for any bin from Unix? e. g. python, php, node and git.

I thought pass the bin name to executable, and he execute `bash -ic '{bin-name} {args}'` command. I try create a similar program in Java, but not work :(

I execute the `java -jar myProgram.jar git` for call git in wsl, the return look ok. See:

![run my java program](https://image.prntscr.com/image/YV9w1PuQSz_vRrvJyzGgcA.png)

I missed any thing in returned?

Ps: I already translated the path from windows to unix and unix to windows.

**Comment by andy-5** [comment]
Well, it seems your program works just fine, because it prints the output of git. However, it looks like your current directory is not a git repository. Maybe you just need to run your program inside a repository?

Or what exactly does not work with your program?

For executing arbitrary commands you can also take a look at this fork of my project:

https://github.com/neoantox/wslproxy

It calls a WSL command based on the filename of the Windows executable.

I'm closing this issue, as it is not a problem in `wslgit`. Feel free to ask further questions here, if you want to discuss additional details of your problem.
