### ISSUE TITLE
running wslgit on powershell or cmd gives no output

### ISSUE THREAD

**Issue by py563** [andy-5/wslgit#72]
I copied latest release and updated path but I do not understand what is it doing
```
PS G:\Git_Repos> git --version
PS G:\Git_Repos> git
PS G:\Git_Repos> wsl.exe bash -ic "git --version"
git version 2.17.1
PS G:\Git_Repos> wsl.exe git --version
git version 2.17.1
PS G:\Git_Repos> wslgit -v
PS G:\Git_Repos> wslgit --version
PS G:\Git_Repos> wslgit
PS G:\Git_Repos> wslgit clone https://github.com/py563/yayin.git
PS G:\Git_Repos>
```
System Info: WSL is ubuntu from windows store and Windows 10 Pro Insider Build 18890

**Comment by andy-5** [comment]
Unfortunately, I cannot reproduce this. But I'm not on an Insider Build, so maybe something changed in recent versions.

Does setting the environment variable `WSLGIT_USE_INTERACTIVE_SHELL` change anything? I.e. you could try
```
PS G:\Git_Repos> $env:WSLGIT_USE_INTERACTIVE_SHELL = "0"
PS G:\Git_Repos> wslgit --version
```
(but I see you already tried both variants manually)

To maybe isolate the problem, you could also try to redirect the output. Does
```
wslgit --version > output.txt
```
write anything to the file `output.txt`?

Also, do you run any anti virus software? Because some have blocked `wslgit` in the past. Can you run `wslgit.exe` by double clicking it (the terminal window should briefly appear and then close itself)? Or is access maybe blocked by some AV software or Windows Defender?

**Comment by py563** [comment]
weird few restarts after some other programs I installed seemed to fix it.. I replaced my hard disk with ssd so I was installing again few old programs.
