### ISSUE TITLE
Question: Will it work with the new style WSL environments?

### ISSUE THREAD

**Issue by ccclausen** [andy-5/wslgit#8]
We read in https://github.com/andy-5/wslgit/issues/4#issuecomment-340285891 that there is a old an new style WSL.

Will the tool made to be work in the new style environment as well? What is the difference?

**Comment by andy-5** [comment]
Yes, it should already work with the [new style WSL distributions](https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/) (installed from the store).

Basically, the issue is, that with the new style WSL, you can install multiple Linux distributions from the Microsoft Store at the same time. Each of them also ships its own Windows binary to run commands in the corresponding environment.

However, I learned that the old way of calling into WSL, by using `bash.exe`, continues to work. The commands then run in the *default distribution*, which is documented [here](https://docs.microsoft.com/en-us/windows/wsl/wsl-config).

As long as Git is installed in the configured default distribution, `wslgit` should just work.
