### ISSUE TITLE
Does not work since around 5. Nov 2017 on PHPStorm anymore

### ISSUE THREAD

**Issue by ccclausen** [andy-5/wslgit#9]
We were successfully using wslgit, but around 5.11. it stopped working.
Then on 8. Nov we found the new release and installed it - still not working.

When we do git actions, four Command Line processes appear in the task manager which consume lots of resources. 

How can this problem be trouble shooted?

**Comment by ccclausen** [comment]
![taskmanager](https://user-images.githubusercontent.com/31509964/33661880-05d02ac0-da8a-11e7-9ee9-93ba233d4c53.PNG)

**Comment by ccclausen** [comment]
We checked the PHPstorm log and saw that the following is executed:

"C:\Program Files\JetBrains\PhpStorm 2017.2.3\bin\runnerw.exe" C:\Windows\git.exe ....

when executing

`"C:\Program Files\JetBrains\PhpStorm 2017.2.3\bin\runnerw.exe" C:\Windows\git.exe` in CMD, it also seems to hang - to the problem does not seem to be directly related to PHPstorm

**Comment by andy-5** [comment]
This is a known bug in WSL since the Fall Creators Update, see https://github.com/Microsoft/WSL/issues/2592

Aparently, it is already fixed in the Insider Builds of Windows, but there is no general update available.

The latest `wslgit` Release ([v3.0.0](https://github.com/andy-5/wslgit/releases/tag/v0.3.0)) fixes this for VS Code by special casing the call to `git --version`, which seems to be the only affected command in the case of VS Code.

However, I suspect that in your case all commands are affected, because they are all performed through the same `runnerw.exe` executable. Or do other commands maybe show a different behaviour? Does something like

`"C:\Program Files\JetBrains\PhpStorm 2017.2.3\bin\runnerw.exe" C:\Windows\git.exe status`

also hang?

Also, the `runnerw.exe` executable seems to have a `/C` command like switch to open a new, visible, console. Maybe this could be a workaround? Could you please try this:

`"C:\Program Files\JetBrains\PhpStorm 2017.2.3\bin\runnerw.exe" /C C:\Windows\git.exe`

**Comment by andy-5** [comment]
With the Windows 10 April 2018 Update now available and several new releases of wslgit, could you maybe test if this is still an issue?

**Comment by n0l0cale** [comment]
hi all,

exactly the same issue with Android Studio. AS claims that git.exe would not work as expected and the processes bash and git remains up to the next reboot. (4 tries to run git each time I start android studio).

a minidump of the file does not contain any exception code.... Maybe some kind of logging would be useful? (startparamters?)

Cheers,
S.

P.S.: Windows Version 1803 (17134.48) with all available updates installed

**Comment by andy-5** [comment]
Thanks for the update. It seems the latest Windows release did not fix the hanging processes, as I hoped.

Could you try setting the Windows environment variable `WSLGIT_USE_INTERACTIVE_SHELL` to `false` (see Readme for more information on that) and check if this changes anything?

Yes, logging would be possible, but it can noticeable slow down execution. I'll look into adding it optionally, or maybe provide a separate executable for testing.

**Comment by andy-5** [comment]
Recent issue #41 suggests that `wslgit` generally works with IntelliJ now, so I'm closing this issue.

Feel free to respond here or open a new issue if you still have any problems.
